apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: kong
data:
  kong.yaml: |
    _format_version: "1.1"
    services:
    - name: ingestion-service
      url: http://ingestion-service.ingestion.svc.cluster.local
      routes:
      - name: example-route
        paths:
        - /
