apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: kong
data:
  kong.yaml: |
    _format_version: "1.1"
    services:
    - name: example-service
      url: http://example.com
      routes:
      - name: example-route
        paths:
        - /
