apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: docker.io/library/gateway:latest
          imagePullPolicy: Never
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /kong/declarative/kong.yml
            - name: KONG_PLUGINS
              value: "bundled"
            - name: KONG_NGINX_DAEMON
              value: "off"
            - name: KONG_REDIS_HOST
              value: "redis.kong.svc.cluster.local"
            - name: KONG_REDIS_PORT
              value: "6379"
            - name: KONG_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kong-redis
                  key: redis-password
          volumeMounts:
            - name: kong-config-volume
              mountPath: /kong/declarative/kong.yml
              subPath: kong.yaml
      volumes:
        - name: kong-config-volume
          configMap:
            name: kong-config