name: Unit Tests
on:
  push:
    branches:
      - master 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Setup wire
        run: go install github.com/google/wire/cmd/wire@latest

      - name: Install dependencies
        run: go mod tidy
      
      - name: Run Tests
        run: ./scripts/test.sh
