apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: gateway-redis
spec:
  replicas: 6
  selector:
    matchLabels:
      app: redis-cluster
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          command: ["redis-server", "--cluster-enabled", "yes"]