apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: temporal
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432  # Port used by PostgreSQL
      targetPort: 5432  # Port on which PostgreSQL is listening
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-service
  namespace: temporal
spec:
  selector:
    app: temporal
  ports:
    - protocol: TCP
      port: 7233
      targetPort: 7233
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui-service
  namespace: temporal
spec:
  type: NodePort
  selector:
    app: temporal-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
